created patch since its crashing(TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)) in ios side BackHandler.removeEventListener .removeEventListener has been deprecated in newer versions of React Native (especially 0.65+)